.TH PYCOWSAY 6 "12 October 2023" "0.0.0.1"
.SH NAME
pycowsay \- a talking cow
.SH SYNOPSIS
.SY pycowsay
.RI [ message \&.\|.\|.]\&
.YS
.SY pycowsay
.B \-\-help
.YS
.SY pycowsay
.B \-\-version
.YS
.SH DESCRIPTION
.B pycowsay
generates an ASCII picture of a cow saying something provided by the user. The
command-line arguments
.I message
are the cow's message.
.SH OPTIONS
.TP
.BR \-\-help
Print a help message and exit.
.TP
.BR \-\-version
Display version information.
.SH EXIT STATUS
.B pycowsay
always exits with status 0.
.SH REPORTING BUGS
Report bugs on
.UR https://\:github.com/\:cs01/\:pycowsay/\:issues
GitHub
.UE .
.SH COPYRIGHT
Copyright (c) 2019-2023 Chad Smith. This program is distributed under an MIT
license. See the file
.I LICENSE
distributed with this program for details.
.SH SEE ALSO
.BR cowsay (6)
